var callsList = [
  {
    "id": "1234",
    "fullName": "Adwerd",
    "phoneNumber": "+91 92345 41561",
    "location": "Delhi",
    "audioFileLoc": "",
    "imageIcon":"/user/avatar-1.jpg",
    "timeStamp": "11 MAY 12:56",
    "callDuration": "Idk",
    "callPurpose": "Panic flood",
    "prediction":"",
  },
  {
    "id": "1235",
    "fullName": "Adwerd1",
    "phoneNumber": "+91 92345 41561",
    "location": "Delhi",
    "audioFileLoc": "",
    "imageIcon":"/user/avatar-2.jpg",
    "timeStamp": "11 MAY 12:56",
    "callDuration": "Idk",
    "callPurpose": "Panic flood",
    "prediction":"",
  },
  {
    "id": "1236",
    "fullName": "Adwerd2",
    "phoneNumber": "+91 92345 41561",
    "location": "Delhi",
    "audioFileLoc": "",
    "imageIcon":"/user/avatar-3.jpg",
    "timeStamp": "11 MAY 12:56",
    "callDuration": "Idk",
    "callPurpose": "Panic flood",
    "prediction":"",
  },
  {
    "id": "1237",
    "fullName": "Adwerd3",
    "phoneNumber": "+91 92345 41561",
    "location": "Delhi",
    "audioFileLoc": "",
    "imageIcon":"/user/avatar-1.jpg",
    "timeStamp": "11 MAY 12:56",
    "callDuration": "Idk",
    "callPurpose": "Panic flood",
    "prediction":"",
  },
  {
    "id": "1238",
    "fullName": "Adwerd4",
    "phoneNumber": "+91 92345 41561",
    "location": "Delhi",
    "audioFileLoc": "",
    "imageIcon":"/user/avatar-2.jpg",
    "timeStamp": "11 MAY 12:56",
    "callDuration": "Idk",
    "callPurpose": "Panic flood",
    "prediction":"",
  },
];

export default callsList;